# Решение систем линейных уравнений методом Крамера
\begin{cases}
  5x - y - z = 0 &\\
  x + 2y + 3z = 14 &\\
  4x + 3y + 2z = 16 &
\end{cases}

In [2]:
import numpy as np

In [3]:
a1 = [5, 1, 4]
a2 = [-1, 2, 3]
a3 = [-1, 3, 2]
b = [0, 4, 16]

В матричном виде эта система может быть записана как $A \times X = B$, где $A$ - основная матрица системы, ее элементами являются коэффициенты при неизвестных переменных, $B$ - матрица – столбец свободных членов

In [4]:
A = np.transpose(np.matrix([a1, a2, a3]))
print(A)

[[ 5 -1 -1]
 [ 1  2  3]
 [ 4  3  2]]


In [5]:
B = np.transpose(np.matrix([b]))
print(B)

[[ 0]
 [ 4]
 [16]]


Определяем вспомогательные матрицы

In [8]:
A1 = np.transpose(np.matrix([b, a2, a3]))
print(A1)

[[ 0 -1 -1]
 [ 4  2  3]
 [16  3  2]]


In [9]:
A2 = np.transpose(np.matrix([a1, b, a3]))
print(A2)

[[ 5  0 -1]
 [ 1  4  3]
 [ 4 16  2]]


In [10]:
A3 = np.transpose(np.matrix([a1, a2, b]))
print(A3)

[[ 5 -1  0]
 [ 1  2  4]
 [ 4  3 16]]


Находим определители главной и вспомогательной матриц

In [11]:
A_det = round(np.linalg.det(A))
A1_det = round(np.linalg.det(A1))
A2_det = round(np.linalg.det(A2))
A3_det = round(np.linalg.det(A3))
print(f"|A| = {A_det}")
print(f"|A1| = {A1_det}")
print(f"|A2| = {A2_det}")
print(f"|A3| = {A3_det}")

|A| = -30
|A1| = -20
|A2| = -200
|A3| = 100


Находим неизвестные

In [27]:
x = A1_det / A_det
y = A2_det / A_det
z = A3_det / A_det
print(f"x = {x:.3f}")
print(f"y = {y:.3f}")
print(f"z = {z:.3f}")

x = 0.667
y = 6.667
z = -3.333


Сделаем проверку

In [33]:
znach = round(a1[0]*x + a2[0]*y + a3[0]*z)
print(f"{a1[0]}*({x:.3f}) + ({a2[0]})*({y:.3f}) + ({a3[0]})*({z:.3f}) = {znach}")
if znach == b[0]:
    print("Проверка пройдена")
else:
    print("Проверка не пройдена")

5*(0.667) + (-1)*(6.667) + (-1)*(-3.333) = 0
Проверка пройдена
