# Решение систем линейных уравнений матричным методом

\begin{cases}
  5x - y - z = 0 &\\
  x + 2y + 3z = 14 &\\
  4x + 3y + 2z = 16 &
\end{cases}

In [2]:
import numpy as np

Обозначим отдельно как A матрицу коэффициентов при неизвестных и как B матрицу неизвестных и матрицу свободных членов

In [9]:
a = np.matrix('5 -1 -1; 1 2 3; 4 3 2')
print(a)

[[ 5 -1 -1]
 [ 1  2  3]
 [ 4  3  2]]


In [4]:
b = np.matrix('0; 14; 16')
print(b)

[[ 0]
 [14]
 [16]]


Сначала проверим, не является ли матрица коэффициентов при неизвестных вырожденной, то есть можем ли вообще применять матричный метод

In [5]:
a_det = np.linalg.det(a)
print(f"|A| = {a_det}")

|A| = -30.000000000000004


Определитель этой матрицы не равен нулю, следовательно, 
можем применять матричный метод.

Решение системы линейных алгебраических уравнений матричным методом определяется по формуле $X = A^{-1} \times B$

Определим обратную матрицу А

In [6]:
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.16666667  0.03333333  0.03333333]
 [-0.33333333 -0.46666667  0.53333333]
 [ 0.16666667  0.63333333 -0.36666667]]


Находим матрицу неизвестных

In [7]:
X = a_inv.dot(b)
print(X)

[[1.]
 [2.]
 [3.]]


Итак, получили решение

In [8]:
x = int(round(X[0, 0]))
y = int(round(X[1, 0]))
z = int(round(X[2, 0]))         
print(f"x = {x}")
print(f"y = {y}")
print(f"z = {z}")

x = 1
y = 2
z = 3


Сделаем проверку

In [10]:
znach = a[0,0]*x + a[0,1]*y + a[0,2]*z
print(f"{a[0,0]}*{x} + ({a[0,1]})*{y} + ({a[0,2]})*{z} = {b[0,0]}")
if znach == b[0,0]:
    print("Проверка пройдена")
else:
    print("Проверка не пройдена")

5*1 + (-1)*2 + (-1)*3 = 0
Проверка пройдена
