# Задание 1
### Транспонирование матрицы

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [2]:
A = np.matrix('5 7 13; 23 4 9')
print(A)

[[ 5  7 13]
 [23  4  9]]


In [3]:
R = (A.T).T
print(R)

[[ 5  7 13]
 [23  4  9]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [4]:
B = np.matrix('4 3 15; 3 0 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 9 26]
 [10  4]
 [28 14]]


In [5]:
print(R)

[[ 9 26]
 [10  4]
 [28 14]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [6]:
A = np.matrix('5 7; 3 1')
B = np.matrix('0 4; 3 2')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[21  3]
 [34 14]]


In [7]:
print(R)

[[21  3]
 [34 14]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [8]:
A = np.matrix(' 5 7 13; 23 4 9')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[15 69]
 [21 12]
 [39 27]]


In [9]:
print(R)

[[15 69]
 [21 12]
 [39 27]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [10]:
A = np.matrix('5 7; 3 1')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

-16


In [11]:
print(format(A_T_det, '.9g'))

-16
