# Задание 2
### Умножение матрицы на число

In [1]:
import numpy as np

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [2]:
A = np.matrix('5 7; 3 1')
L = 1 * A
R = A
print(L)

[[5 7]
 [3 1]]


In [3]:
print(R)

[[5 7]
 [3 1]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [4]:
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [5]:
print(R)

[[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [6]:
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[25 35]
 [15  5]]


In [7]:
print(R)

[[25 35]
 [15  5]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [8]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[30 42]
 [18  6]]


In [9]:
print(R)

[[30 42]
 [18  6]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [10]:
B = np.matrix('0 4; 3 2')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[15 33]
 [18  9]]


In [11]:
print(R)

[[15 33]
 [18  9]]
