# Задание 6
### Обратная матрица

In [1]:
import numpy as np

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [2]:
A = np.matrix('11. -2.; -3. 15.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[11. -2.]
 [-3. 15.]]


In [3]:
print(A_inv_inv)

[[11. -2.]
 [-3. 15.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [4]:
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[0.09433962 0.01886792]
 [0.01257862 0.06918239]]


In [5]:
print(R)

[[0.09433962 0.01886792]
 [0.01257862 0.06918239]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [6]:
B = np.matrix('9. -1.; 13. 4.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.00808625  0.00243871]
 [-0.02156334  0.00936979]]


In [7]:
print(R)

[[ 0.00808625  0.00243871]
 [-0.02156334  0.00936979]]
